- type: job
  id: CrewChief
  name: job-name-crew-chief
  description: job-description-crew-chief
  playTimeTracker: JobCrewChief
  startingGear: CrewChiefGear
  icon: "JobIconQuarterMaster"
  supervisors: job-supervisors-station-administrator
  access:
  - CoalitionCommand
  - CoalitionBasic
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skill
        helmJobModifier: 30
        weaponsJobModifier: 15
        mechanicalEngineeringJobModifier: 10
        electricalEngineeringJobModifier: 10
        medicalJobModifier: 15

- type: startingGear
  id: CrewChiefGear
  equipment:
    jumpsuit: BS14-ClothingUniformCrewChiefOutfit
    id: PassengerIDCard
    ears: BS14-ClothingHeadset